anchor_job_defaults: &job_defaults
  working_directory: ~/mosaic-icons
  docker:
    - image: ptsecurity/node-container:0.0.4

version: 2
jobs:
  build:
    <<: *job_defaults
    resource_class: large
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: icons-cache-{{ checksum "package.json" }}
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install npm packages
          command: npm install
      - save_cache:
          key: icons-cache-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run build
          command: bash ./scripts/build.sh
  publish:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+(?:\.\d+)*$/